### PR TITLE
Add production fingerprinting instructions

### PR DESCRIPTION
**Pull request by syndbg**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe:

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

**Other information**:

Added production fingerprinting instructions to the `README.md`.

### CODE REVIEW

**Comment by andreicek** [comment]
Hi!

First of all, I would like to thank you for your time and contribution! :tada: Can you explain a bit more why the exact format is needed?

What you use in the example is:

```
'[name]-bundle.js-chunkhash-[chunkhash]'
```

When a version of the code that would replicate the gain would look like:

```
'[name]-bundle-chunkhash-[chunkhash].js'
```

or even 

```
'[name]-bundle-chunkhash-[hash].js'
```

In those two cases, Webpack would handle the names and report the "correct" one.

``` JavaScript
{
  "main.js": "main-bundle-chunkhash-aaefcea3d6d1f037c822-bundle.js"
}
```

If you think that that exact format is important we'll automate the process for using it (cleaning up the filename).

Again, thanks!

**Comment by andreicek** [comment]
@gabskoro Would love your input as well!

**Comment by syndbg** [comment]
@andreicek No particular reason whatsoever. I wasn't aware that Webpack would automagically strip the `[chunkhash]`if it's in the filename.  👍 

Just `'[name]-bundle-[chunkhash].js',` does the job.

If it's worth adding this in the docs, I would modify the PR. Either way you solved my problem without the need of a custom key function 😄

**Comment by andreicek** [comment]
Thanks for the clarification!

The README is getting a bit crowded so I'll have to rework it and separate it into different files or something like that. I've created an issue #17 for this to handle. We'll have to decide how before we write a new README.

**Pull request closed without merging**
